---
apiVersion: v1
kind: Service
metadata:
  name: customer-service-app
  namespace: neuralbank
  labels:
    app: customer-service-app
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: customer-service-app
  type: ClusterIP