{{- if eq .Values.image.registry "Quay" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quarkus-build.name" . }}-registry-creds
  annotations:
    tekton.dev/docker-0: https://{{ .Values.image.host }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "{{ .Values.image.host }}": {
          "auth": "{{ printf "%s:%s" .Values.image.organization .Values.image.password | b64enc }}"
        }
      }
    }
{{- end }}